# Generated by Django 4.2.9 on 2026-03-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PUBLIC', 'Public'), ('ADMIN', 'Admin'), ('CONDUCTOR', 'Conductor')], default='STUDENT', max_length=15),
        ),
    ]
