# Generated by Django 4.2.9 on 2026-04-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='route',
            new_name='route_from',
        ),
        migrations.AddField(
            model_name='user',
            name='route_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
