# Generated by Django 4.2.9 on 2026-04-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_route_user_route_from_user_route_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='route_from',
            new_name='route',
        ),
        migrations.RemoveField(
            model_name='user',
            name='route_to',
        ),
    ]
