# Generated by Django 4.2.9 on 2026-04-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_route_from_user_route_remove_user_route_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='route',
            new_name='route_from',
        ),
        migrations.AddField(
            model_name='user',
            name='route_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
