# Generated by Django 4.2.9 on 2026-04-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_route_user_route_from_user_route_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bus_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
