# Generated by Django 4.2.9 on 2026-04-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_bus_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bus_number',
        ),
    ]
