# Generated by Django 4.2.9 on 2026-04-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bus_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
