# Generated by Django 4.2.9 on 2026-04-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_bus_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bus_route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
