# Generated by Django 4.2.28 on 2026-02-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_pass_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('pass_type', models.CharField(choices=[('STUDENT', 'Student'), ('PUBLIC', 'Public')], max_length=10)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('trip_number', models.IntegerField()),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('main_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='passes.mainpass')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('renewal_date', models.DateField(auto_now_add=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('main_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='passes.mainpass')),
            ],
        ),
    ]
