# Generated by Django 4.2.28 on 2026-02-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpass',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10),
        ),
    ]
