# Generated by Django 4.2.9 on 2026-03-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0003_mainpass_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpass',
            name='daily_trip_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mainpass',
            name='last_used_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
