# Generated by Django 4.2.9 on 2026-03-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0004_mainpass_daily_trip_count_mainpass_last_used_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpass',
            name='current_valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
