# Generated by Django 4.2.9 on 2026-03-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0005_mainpass_current_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrenewal',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10),
        ),
    ]
