# Generated by Django 4.2.9 on 2026-03-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0006_monthlyrenewal_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrenewal',
            name='renewal_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
