# Generated by Django 4.2.9 on 2026-04-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0007_monthlyrenewal_renewal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpass',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='monthlyrenewal',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
